import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Cards from '../components/Cards'
import Footer from '../components/Footer';
import Header from '../components/Header';
import { HOST } from '../utils';

export default function Home({ days }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Programación FESTIVAL DE LA IMAGEN 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.content}>
                <Header title={"PROGRAMACIÓN"} />
                <Cards days={days} />
                <Footer />
            </main>
        </div>
    )
}

export async function getServerSideProps(context) {
    const res = await fetch(`${HOST}/api/days`);
    const data = await res.json();
    return { props: { days: data } };
}