import Head from "next/head";
import Activities from "../../components/Activities";
import Back from "../../components/Back";
import Footer from "../../components/Footer";
import styles from '../../styles/Activity.module.css';
import { HOST } from "../../utils";

export default function ({ programs, day, event, members }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Sinopsis</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.content}>
                <header className={styles.rotulo}>
                    <Back route={event ? `/programacion/${day.id}` : "/"} />
                </header>
                {event && <Activities activities={programs} event={event} members={members} />}
                <Footer dark />
            </div>
        </div>
    )
}

export async function getServerSideProps(context) {
    const eventQuery = context.query.prog;
    let events = [];
    let programs = null;
    let day = null;
    let members = [];
    let event = null;

    const eventsReq = await fetch(`${HOST}/api/events/`);
    events = await eventsReq.json();
    event = events.find(event => event.id === eventQuery) ?? null;
    if (event) {
        const programsReq = await fetch(`${HOST}/api/programs/${eventQuery}`);
        programs = await programsReq.json();
        const dayQuery = event.day;
        const dayReq = await fetch(`${HOST}/api/days/${dayQuery}`);
        day = await dayReq.json();
        const membersReq = await fetch(`${HOST}/api/members`);
        members = await membersReq.json();
    }

    return { props: { programs, day, event, members: members.filter(member => member.event_id === eventQuery) } };
}